module.exports = () => ({
  assetsBuildPath: 'userRootPath/build/public/',
  buildPath: 'userRootPath/build',
  clientAssetsFile: 'userRootPath/build/publicAssets.json',
  clientBuildPath: 'userRootPath/build/client',
  clientPolyfillsPath: 'userRootPath/src/client/polyfills.js',
  clientSrcPath: 'userRootPath/src/client',
  loadableAssetsFile: 'userRootPath/build/loadable.json',
  prototypeBuildPath: 'userRootPath/build/prototype',
  publicBuildPath: 'userRootPath/build/public',
  publicSrcPath: 'userRootPath/src/public',
  serverBuildPath: 'userRootPath/build/server',
  serverPolyfillsPath: 'userRootPath/src/server/polyfills.js',
  serverSrcPath: 'userRootPath/src/server',
  srcPath: 'userRootPath/src',
  testBuildPath: 'userRootPath/build/test',
  userBabelrcIsEmpty: undefined,
  userBabelrcNotFound: false,
  userBabelrcParsed: {
    presets: ['kyt-react'],
  },
  userBabelrcPath: 'userRootPath/.babelrc',
  userKytConfigIsEmpty: undefined,
  userKytConfigNotFound: false,
  userKytConfigParsed: {
    debug: false,
    reactHotLoader: true,
  },
  userKytConfigPath: 'userRootPath/kyt.config.js',
  userNodeModulesPath: 'userRootPath/node_modules',
  userPackageJSONPath: 'userRootPath/package.json',
  userPostcssConfigIsEmpty: undefined,
  userPostcssConfigNotFound: false,
  userPostcssConfigParsed: {
    plugins: {
      foo: false,
    },
  },
  userPostcssConfigPath: 'userRootPath/postcss.config.js',
  userPrototypePath: 'userRootPath/prototype.js',
  userRootPath: 'userRootPath',
});
