# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://nytimes.github.io/kyt/
title: kyt
author: The New York Times Company
description: > # "Write an awesome description for your new site here. 
  Every sizable JavaScript web app needs a common
  foundation: a setup to build, run, test and lint
  your code. kyt is a toolkit that encapsulates and
  manages the configuration for web apps.
copyright: 'Copyright &copy; 2016 The New York Times Company'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: blog post
    icon: blog
    url: http://open.blogs.nytimes.com/2016/09/13/introducing-kyt-our-web-app-configuration-toolkit/
  - title: github
    url: https://github.com/NYTimes/kyt
  - title: npm
    icon: code
    url: https://www.npmjs.com/package/kyt
