name: Continuous Integration

on: [push, pull_request]

jobs:
  kyt-tests:
    name: "Test with Node LTS Versions"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn exec lerna run prepare
    - run: yarn lint:ci
    - run: yarn test:ci
    - run: yarn e2e
