name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  kyt-tests:
    name: "Lint, Test with Node"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn exec lerna run prepare
    - run: yarn lint:ci
    - run: yarn test:ci
    - run: yarn e2e
